fix(azure): use regular storage instead of premium
premium storage does not support block blobs, whereas regular storage does.

Error coming from wal-e:

```
azure.storage._http.HTTPError: Block blobs are not supported.
```